{
 "title": "Idle metrics",
 "description": "A quick and simple dashboard for viewing how your vertical pod autoscaler is doing.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "query": "label_values(cnvrg_filesystem_event_total{}, pod)"
   },
   { "name": "idle_timeout", "query": "60m" }
  ]
 },
 "panels": [
  {
   "title": "File changes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 16, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cnvrg_filesystem_event_total{service=~\".*$pod.*\"}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(sum(rate(container_cpu_usage_seconds_total{container=\"slave\", name=~\".*$pod.*\"}[5m])) by (instance)[${idle_timeout}:]) * 100"
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=~\".*$pod.*\", resource=\"cpu\"}"
    },
    {}
   ]
  },
  {
   "title": "Memory utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "(avg_over_time(container_memory_working_set_bytes{container=\"slave\", name=~\".*$pod.*\"}[$idle_timeout]) / on (instanse) kube_pod_container_resource_limits_memory_bytes{pod=~\".*$pod.*\"}) * 100"
    }
   ]
  },
  {
   "title": "GPU Memory utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(DCGM_FI_DEV_MEM_COPY_UTIL{container=\"slave\", exported_pod=~\".*$pod.*\"}[${idle_timeout}])"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(DCGM_FI_DEV_GPU_UTIL{container=\"slave\", exported_pod=~\".*$pod.*\"}[${idle_timeout}])"
    }
   ]
  }
 ]
}