{
 "title": "pgBackRest",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": "label_values(pg_cluster)" }
  ]
 },
 "panels": [
  {
   "title": "Time Since Last Completed Backup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ccp_backrest_last_incr_backup_time_since_completion_seconds{pg_cluster=\"[[cluster]]\", role=\"master\"}",
     "legendFormat": "Full"
    },
    {
     "expr": "ccp_backrest_last_diff_backup_time_since_completion_seconds{pg_cluster=\"[[cluster]]\", role=\"master\"}",
     "legendFormat": "Diff"
    },
    {
     "expr": "ccp_backrest_last_full_backup_time_since_completion_seconds{pg_cluster=\"[[cluster]]\", role=\"master\"}",
     "legendFormat": "Incr"
    }
   ]
  },
  {
   "title": "Backup Runtimes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ccp_backrest_last_info_backup_runtime_seconds{pg_cluster=\"[[cluster]]\", role=\"master\", backup_type=\"full\"}",
     "legendFormat": "Full"
    },
    {
     "expr": "ccp_backrest_last_info_backup_runtime_seconds{pg_cluster=\"[[cluster]]\", role=\"master\", backup_type=\"diff\"}",
     "legendFormat": "Diff"
    },
    {
     "expr": "ccp_backrest_last_info_backup_runtime_seconds{pg_cluster=\"[[cluster]]\", role=\"master\", backup_type=\"incr\"}",
     "legendFormat": "Incr"
    }
   ]
  }
 ]
}
{
 "title": "CRUD_Details",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(pg_cluster)" },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values({pg_cluster=\"[[cluster]]\"},pod)"
   },
   {
    "name": "dbname",
    "label": "dbname",
    "query": "label_values(ccp_database_size_bytes{pg_cluster=\"[[cluster]]\"},dbname)"
   },
   {
    "name": "schemaname",
    "label": "schemaname",
    "query": "label_values(ccp_stat_user_tables_n_tup_ins{pg_cluster=\"[[cluster]]\",dbname=~\"[[dbname]]\"},schemaname)"
   },
   {
    "name": "tablename",
    "query": "label_values(ccp_stat_user_tables_n_tup_ins{pg_cluster=\"[[cluster]]\",dbname=~\"[[dbname]]\",schemaname=~\"[[schemaname]]\"},relname)"
   }
  ]
 },
 "panels": [
  {
   "title": "CRUD",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ccp_stat_user_tables_n_tup_ins{pg_cluster=\"[[cluster]]\", pod=~\"[[pod]]\", dbname=~\"[[dbname]]\", schemaname=~\"[[schemaname]]\", relname=~\"[[tablename]]\"}[60s]))",
     "legendFormat": "inserts - [[dbname]].[[schemaname]].[[tablename]]"
    },
    {
     "expr": "sum(rate(ccp_stat_user_tables_n_tup_upd{pg_cluster=\"[[cluster]]\", pod=~\"[[pod]]\", dbname=~\"[[dbname]]\", schemaname=~\"[[schemaname]]\", relname=~\"[[tablename]]\"}[60s]))",
     "legendFormat": "Updates - [[dbname]].[[schemaname]].[[tablename]]"
    },
    {
     "expr": "sum(rate(ccp_stat_user_tables_n_tup_del{pg_cluster=\"[[cluster]]\", pod=~\"[[pod]]\", dbname=~\"[[dbname]]\", schemaname=~\"[[schemaname]]\", relname=~\"[[tablename]]\"}[60s]))",
     "legendFormat": "Deletes - [[dbname]].[[schemaname]].[[tablename]]"
    }
   ]
  }
 ]
}
{
 "title": "POD Details",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": "label_values(pg_cluster)" },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values({pg_cluster=\"[[cluster]]\"},pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(ccp_nodemx_data_disk_total_bytes{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}-ccp_nodemx_data_disk_available_bytes{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})*100/ccp_nodemx_data_disk_total_bytes{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "{{ '{{' }}mount_point{{ '}}' }} "
    },
    {
     "expr": "(ccp_nodemx_data_disk_total_file_nodes{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}-ccp_nodemx_data_disk_free_file_nodes{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})*100/ccp_nodemx_data_disk_total_file_nodes{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "{{ '{{' }}mount_point{{ '}}' }} - Inodes"
    }
   ]
  },
  {
   "title": "Disk Activity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(ccp_nodemx_disk_activity_sectors_read{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}[1m])*512",
     "legendFormat": "{{ '{{' }}mount_point{{ '}}' }} - Reads"
    },
    {
     "expr": "rate(ccp_nodemx_disk_activity_sectors_written{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}[1m])*512",
     "legendFormat": "{{ '{{' }}mount_point{{ '}}' }} - Writes "
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ccp_nodemx_mem_limit{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "ccp_nodemx_mem_request{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "Request"
    },
    {
     "expr": "ccp_nodemx_mem_cache{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "ccp_nodemx_mem_dirty{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "Dirty"
    },
    {
     "expr": "ccp_nodemx_mem_shmem{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "shared mem"
    },
    {
     "expr": "ccp_nodemx_mem_rss{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "ccp_nodemx_mem_mapped_file{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "Mapped file"
    },
    {
     "expr": "ccp_nodemx_mem_active_anon{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "Active anon"
    },
    {
     "expr": "ccp_nodemx_mem_inactive_anon{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "Inactive anon"
    },
    {
     "expr": "ccp_nodemx_mem_active_file{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "Active file"
    },
    {
     "expr": "ccp_nodemx_mem_inactive_file{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "Inactive file"
    }
   ]
  },
  {
   "title": "CPU Stats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((rate(ccp_nodemx_cpuacct_usage{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}[1m]))/1000)*100)/((ccp_nodemx_cpucfs_quota_us{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}/ccp_nodemx_cpucfs_period_us{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})*1000*1000)",
     "legendFormat": "% Used"
    },
    {
     "expr": "rate(ccp_nodemx_cpustat_nr_throttled{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}[1m])*100/rate(ccp_nodemx_cpustat_nr_periods{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}[1m])",
     "legendFormat": "% Throttled"
    },
    {
     "expr": "ccp_nodemx_process_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "Process count"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(ccp_nodemx_network_rx_bytes{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\", interface!=\"tunl0\"}[1m])",
     "legendFormat": "{{ '{{' }}interface{{ '}}' }} - rx bytes"
    },
    {
     "expr": "rate(ccp_nodemx_network_tx_bytes{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\", interface!=\"tunl0\"}[1m])",
     "legendFormat": "{{ '{{' }}interface{{ '}}' }} - tx bytes"
    }
   ]
  },
  {
   "title": "Container resources",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "ccp_nodemx_cpu_limit{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "CPU limit"
    },
    {
     "expr": "ccp_nodemx_cpu_request{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "CPU request"
    },
    {
     "expr": "ccp_nodemx_mem_limit{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "Memory limit"
    },
    {
     "expr": "ccp_nodemx_mem_request{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "Memory request"
    }
   ]
  }
 ]
}
{
 "title": "PostgreSQLDetails",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": "label_values(pg_cluster)" },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values({pg_cluster=\"[[cluster]]\"},pod)"
   },
   {
    "name": "datname",
    "label": "Database",
    "query": "label_values({pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"},dbname)"
   }
  ]
 },
 "panels": [
  {
   "title": "[[cluster]] : Backup Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(ccp_backrest_last_incr_backup_time_since_completion_seconds{pg_cluster=\"[[cluster]]\"} < ccp_backrest_last_diff_backup_time_since_completion_seconds{pg_cluster=\"[[cluster]]\"} or ccp_backrest_last_incr_backup_time_since_completion_seconds{pg_cluster=\"[[cluster]]\"} < ccp_backrest_last_full_backup_time_since_completion_seconds{pg_cluster=\"[[cluster]]\"} or ccp_backrest_last_incr_backup_time_since_completion_seconds{pg_cluster=\"[[cluster]]\"}) "
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",state=\"active\"})*100/sum(pg_settings_max_connections{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})"
    }
   ]
  },
  {
   "title": "Idle In Transaction",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 2 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",state=\"idle in transaction\"})/sum(pg_settings_max_connections{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",state=\"idle\"})*100/sum(pg_settings_max_connections{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})"
    }
   ]
  },
  {
   "title": "TPS -  [[pod]]-[[datname]]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m])) + sum(irate(pg_stat_database_xact_rollback{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Connections -  [[pod]]-[[datname]]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",state=\"idle\"})",
     "legendFormat": "idle"
    },
    {
     "expr": "sum by (state) (pg_stat_activity_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",state=\"idle in transaction\"})",
     "legendFormat": "Idle in txn"
    },
    {
     "expr": "sum by (state) (pg_stat_activity_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",state=\"active\"})",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "database size - [[pod]]-[[datname]]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(ccp_database_size_bytes{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})/(1024*1024)",
     "legendFormat": "Total : [[cluster]]-[[pod]]"
    },
    {
     "expr": "ccp_database_size_bytes{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",dbname=~\"[[datname]]\"}/(1024*1024)",
     "legendFormat": "{{ '{{' }}dbname{{ '}}' }} ({{ '{{' }}pod{{ '}}' }})"
    }
   ]
  },
  {
   "title": "WAL size MB - [[cluster]]-[[pod]]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "ccp_wal_activity_total_size_bytes{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}/(1024*1024)",
     "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Row activity -  [[pod]]- [[datname]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_fetched{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_inserted{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_updated{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "Updated"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_deleted{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Replication Status - [[cluster]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Lag in bytes" }
   ],
   "targets": [
    {
     "expr": "ccp_replication_lag_size_bytes{pg_cluster=\"[[cluster]]\", role!=\"replica\"}",
     "legendFormat": "Replica ({{ '{{' }}replica{{ '}}' }}) lag bytes"
    },
    {
     "expr": "ccp_replication_lag_replay_time{pg_cluster=\"[[cluster]]\", role=\"replica\"}",
     "legendFormat": "Replica ({{ '{{' }}ip{{ '}}' }}) lag time"
    }
   ]
  },
  {
   "title": "Conflicts/DeadLocks - [[pod]] - [[datname]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_deadlocks{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "Conflicts"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "DeadLocks"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio - [[pod]]-[[datname]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\", datid!=\"0\", datname!~\"template0\", datname!~\"template1\"}*100/(pg_stat_database_blks_hit{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\", datname!~\"template0\", datname!~\"template1\"} + pg_stat_database_blks_read{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname!~\"template0\", datname!~\"template1\"})",
     "legendFormat": "{{ '{{' }}datname{{ '}}' }} - ({{ '{{' }}pod{{ '}}' }})"
    }
   ]
  },
  {
   "title": "Buffers - [[pod]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ccp_stat_bgwriter_buffers_alloc{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(ccp_stat_bgwriter_buffers_backend{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "sum(ccp_stat_bgwriter_buffers_backend_fsync{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})",
     "legendFormat": "FSync"
    },
    {
     "expr": "sum(ccp_stat_bgwriter_buffers_checkpoint{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})",
     "legendFormat": "CheckPoint"
    },
    {
     "expr": "sum(ccp_stat_bgwriter_buffers_clean{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})",
     "legendFormat": "Clean"
    }
   ]
  },
  {
   "title": "Commit & Rollback",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "Commit"
    },
    {
     "expr": "sum(irate(pg_stat_database_xact_rollback{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "title": "Locks - [[pod]] - [[datname]]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (pg_locks_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",mode=\"accessexclusivelock\"})",
     "legendFormat": "{{ '{{' }}mode{{ '}}' }}"
    },
    {
     "expr": "sum by (mode) (pg_locks_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",mode=\"exclusivelock\"})",
     "legendFormat": "{{ '{{' }}mode{{ '}}' }}"
    },
    {
     "expr": "sum by (mode) (pg_locks_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",mode=\"rowexclusivelock\"})",
     "legendFormat": "{{ '{{' }}mode{{ '}}' }}"
    },
    {
     "expr": "sum by (mode) (pg_locks_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",mode=\"sharerowexclusivelock\"})",
     "legendFormat": "{{ '{{' }}mode{{ '}}' }}"
    },
    {
     "expr": "sum by (mode) (pg_locks_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",mode=\"shareupdateexclusivelock\"})",
     "legendFormat": "{{ '{{' }}mode{{ '}}' }}"
    },
    {
     "expr": "sum by (mode) (pg_locks_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",mode=\"accesssharelock\"})",
     "legendFormat": "{{ '{{' }}mode{{ '}}' }}"
    }
   ]
  }
 ]
}
{
 "title": "PostgreSQL Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": "label_values(pg_cluster)" }
  ]
 },
 "panels": [
  {
   "title": "$cluster - Overview",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "repeat": "cluster",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "$hashKey": "object:243",
     "expr": "sum(pg_up{pg_cluster=~\"$cluster\"})*100+sum(ccp_is_in_recovery_status{pg_cluster=~\"$cluster\"})",
     "legendFormat": "{{ '{{' }}cluster{{ '}}' }}"
    }
   ]
  }
 ]
}
{
 "title": "PostgreSQL Service Health Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(pg_cluster)" },
   {
    "name": "role",
    "query": "label_values({pg_cluster=\"[[cluster]]\"},role)"
   }
  ]
 },
 "panels": [
  {
   "title": "Saturation (pct used)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * ccp_connection_stats_total{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"} / ccp_connection_stats_max_connections{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}",
     "legendFormat": "connections"
    },
    {
     "expr": "100 - 100 * ccp_nodemx_data_disk_available_bytes{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"} / ccp_nodemx_data_disk_total_bytes{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}",
     "legendFormat": "Mount:{{ '{{' }}mount_point{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(irate(ccp_stat_database_xact_commit{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}[1m]))\n+ sum(irate(ccp_stat_database_xact_rollback{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}[1m]))",
     "legendFormat": "Transactions per minute"
    },
    {
     "expr": "ccp_connection_stats_active{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}",
     "legendFormat": "Active connections"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Errors",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ccp_stat_database_deadlocks{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}[1m]))",
     "legendFormat": "Deadlock "
    },
    {
     "expr": "sum(irate(ccp_stat_database_conflicts{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}[1m]))",
     "legendFormat": "Conflicts"
    },
    {
     "expr": "pg_exporter_last_scrape_error{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}",
     "legendFormat": "scrape error"
    },
    {
     "expr": "clamp_max(ccp_archive_command_status_seconds_since_last_fail{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"},1)",
     "legendFormat": "archive error"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "ccp_connection_stats_max_query_time{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}
{
 "title": "PostgreSQL Queries Overview (Designed for PMM)",
 "description": "PostgreSQL Queries Overview Dashboard",
 "tags": [
  "PostgreSQL",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "host", "label": "Host", "query": "label_values(pg_up,instance)" },
   {
    "name": "datname",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{instance=\"$host\",datname!~\"template.*\"},datname)"
   }
  ]
 },
 "panels": [
  { "title": "Statements Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Statements Calls",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_statements_calls{datname=~\"$datname\",instance=~\"$host\"}[$interval]) or \nirate(pg_stat_statements_calls{datname=~\"$datname\",instance=~\"$host\"}[5m])))",
     "legendFormat": "{{ '{{' }}datname{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Most Called Queries",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_calls{datname=~\"$datname\",instance=~\"$host\"}[$interval]) or \nirate(pg_stat_statements_calls{datname=~\"$datname\",instance=~\"$host\"}[5m])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Slowest Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total Duration of Queries",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_statements_time_milliseconds{datname=~\"$datname\",instance=\"$host\"}[$interval]) or \nirate(pg_stat_statements_time_milliseconds{datname=~\"$datname\",instance=\"$host\"}[5m])) > 0)",
     "legendFormat": "{{ '{{' }}datname{{ '}}' }}"
    }
   ]
  },
  {
   "title": "Queries Duration",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sort_desc(topk(10,rate(pg_stat_statements_time_milliseconds{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Runtime",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "topk(10, rate(pg_stat_statements_time_milliseconds{datname=~\"$datname\",instance=~\"$host\"}[$interval]) / \n(rate(pg_stat_statements_calls{datname=~\"$datname\",instance=~\"$host\"}[$interval])))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Shared Blocks I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Shared Blocks Dirtied",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (datname) (rate(pg_stat_statements_shared_blks_dirtied{datname=~\"$datname\",instance=\"$host\"}[$interval]))",
       "legendFormat": "{{ '{{' }}datname{{ '}}' }}"
      }
     ]
    },
    {
     "title": "Total Shared Blocks Catch Hits",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (datname) (rate(pg_stat_statements_shared_blks_hit{datname=~\"$datname\",instance=\"$host\"}[$interval]))",
       "legendFormat": "{{ '{{' }}datname{{ '}}' }}"
      }
     ]
    },
    {
     "title": "Top Shared Blocks  Dirtied",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_shared_blks_dirtied{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top Shared Block Cache Hits",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_shared_blks_hit{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Shared Blocks Read",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum by (datname) (rate(pg_stat_statements_shared_blks_read{datname=~\"$datname\",instance=\"$host\"}[$interval]))",
       "legendFormat": "{{ '{{' }}datname{{ '}}' }}"
      }
     ]
    },
    {
     "title": "Total Shared Blocks Written",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (datname) (rate(pg_stat_statements_shared_blks_written{datname=~\"$datname\",instance=\"$host\"}[$interval]))",
       "legendFormat": "{{ '{{' }}datname{{ '}}' }}"
      }
     ]
    },
    {
     "title": "Top Shared Blocks Read",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_shared_blks_read{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top Shared Blocks Written",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_shared_blks_written{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Local Blocks I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Local Blocks Dirtied",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (datname) (rate(pg_stat_statements_local_blks_dirtied{datname=~\"$datname\",instance=\"$host\"}[$interval]) * 8)",
       "legendFormat": "{{ '{{' }}datname{{ '}}' }}"
      }
     ]
    },
    {
     "title": "Total Local Blocks Cache Hits",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum by (datname) (rate(pg_stat_statements_local_blks_hit{datname=~\"$datname\",instance=\"$host\"}[$interval]))",
       "legendFormat": "{{ '{{' }}datname{{ '}}' }}"
      }
     ]
    },
    {
     "title": "Top Local Blocks Dirtied",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_local_blks_dirtied{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top Local Blocks Cache Hits",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_local_blks_hit{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Local Blocks Read",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum by (datname) (rate(pg_stat_statements_local_blks_read{datname=~\"$datname\",instance=\"$host\"}[$interval]))",
       "legendFormat": "{{ '{{' }}datname{{ '}}' }}"
      }
     ]
    },
    {
     "title": "Total Local Blocks Written",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum by (datname) (rate(pg_stat_statements_local_blks_written{datname=~\"$datname\",instance=\"$host\"}[$interval]))",
       "legendFormat": "{{ '{{' }}datname{{ '}}' }}"
      }
     ]
    },
    {
     "title": "Top Local Blocks Read",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_local_blks_read{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top Local Blocks Written",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 58 },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_local_blks_written{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Temp Data Read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Temp Blocks Read",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum by (datname) (rate(pg_stat_statements_temp_blks_read{datname=~\"$datname\",instance=\"$host\"}[$interval]) or \nirate(pg_stat_statements_temp_blks_read{datname=~\"$datname\",instance=\"$host\"}[5m]))",
       "legendFormat": "{{ '{{' }}datname{{ '}}' }}"
      }
     ]
    },
    {
     "title": "Top Temp Blocks Read",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_temp_blks_read{datname=~\"$datname\",instance=~\"$host\"}[$interval])))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "test1",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Top Temp Blocks Read per Call",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "topk(10, rate(pg_stat_statements_temp_blks_read{datname=~\"$datname\",instance=~\"$host\"}[$interval]) / \n(rate(pg_stat_statements_calls{datname=~\"$datname\",instance=~\"$host\"}[$interval])))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Temp Data Written",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temp Blocks Written",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "wps" }
     ],
     "targets": [
      {
       "expr": "sum by (datname) (rate(pg_stat_statements_temp_blks_written{datname=~\"$datname\",instance=\"$host\"}[$interval]))",
       "legendFormat": "{{ '{{' }}datname{{ '}}' }}"
      }
     ]
    },
    {
     "title": "Temp Blocks Written",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sort_desc(topk(10,rate(pg_stat_statements_temp_blks_written{datname=~\"$datname\",instance=\"$host\"}[$interval])))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Temp Blocks Written per Call",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "topk(10, rate(pg_stat_statements_temp_blks_written{datname=~\"$datname\",instance=\"$host\"}[$interval]) / \n(rate(pg_stat_statements_calls{datname=~\"$datname\",instance=~\"$host\"}[$interval])>1/6000))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "New Slow Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "New Slow Queries for All Databases",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sort_desc(topk(5,sum(irate(pg_stat_statements_time_milliseconds{instance=~\"$host\"}[10m])) by (queryid, datname, user)) unless \ntopk(20,sum(irate(pg_stat_statements_time_milliseconds{instance=~\"$host\"}[10m] offset 7d)) by (queryid, datname, user)))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}