{
 "title": "Kubernetes / Vertical Pod Autoscaler",
 "description": "A quick and simple dashboard for viewing how your vertical pod autoscaler is doing.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values({job=\"kube-state-metrics\"}, namespace)"
   },
   {
    "name": "deployment",
    "query": "label_values(kube_verticalpodautoscaler_labels{job=\"kube-state-metrics\"}, target_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Target Cpu",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target{job=\"kube-state-metrics\", namespace=\"$namespace\", target_name=\"$deployment\", unit=\"core\"}"
    }
   ]
  },
  {
   "title": "Requested Cpu",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1,kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=~\".*$deployment.*\", unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Target Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target{job=\"kube-state-metrics\", namespace=\"$namespace\", target_name=\"$deployment\", unit=\"byte\"}"
    }
   ]
  },
  {
   "title": "Requested Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1,kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=~\".*$deployment.*\", unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "Memory --- Current + Target",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target{job=\"kube-state-metrics\", namespace=\"$namespace\", target_name=\"$deployment\", unit=\"byte\"}"
    },
    {
     "expr": "topk(1,kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=~\".*$deployment.*\", unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "CPU --- Current + Target",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_verticalpodautoscaler_status_recommendation_containerrecommendations_target{job=\"kube-state-metrics\", namespace=\"$namespace\", target_name=\"$deployment\", unit=\"core\"}"
    },
    {
     "expr": "topk(1,kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", container=~\".*$deployment.*\", unit=\"core\"})"
    }
   ]
  }
 ]
}